services:

  certbot:
    image: tmuncks/certbot:latest
    environment:
      - CERTBOT_ONESHOT=0
      - DNS_POWERDNS_API_URL=https://api.mypowerdns.example.org
      - DNS_POWERDNS_API_KEY=AbCbASsd!@34
    command: >-
        certonly
        --email noreply@example.com --agree-tos --no-eff-email
        --domain example.com
    volumes:
      - ./certbot:/etc/letsencrypt
